name: '${name}'
version: '${version}'
main: '${main}'

authors:
  - Drak

folia-supported: true

depend:
  - BukkitOfUtils

commands:
  worldback:
    description: Return to a back of a certain world.
    permission: worldback.commands.worldback
  worldset:
    description: Edit a WorldSet.
    permission: worldback.commands.worldset